services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./app:/rss_reader/app
      - ./templates:/rss_reader/templates
      - ./static:/rss_reader/static
      - db:/db
    ports:
      - 8080:80
    environment:
      FLASK_ENV: development
      DEBUG: "true"
    command: >
      sh -c "uwsgi uwsgi.ini --py-autoreload 2"

  static:
    build:
      context: .
      dockerfile: ./docker/static.Dockerfile
    volumes:
      - ./static:/home/node/rss_reader
    environment:
      SHELL: sh
    command: >
      sh -c "npm run build && npm run watch"

volumes:
  db:
