services:
  app:
    build:
      context: .
    volumes:
      - ./app:/rss_reader/app
      - ./templates:/rss_reader/templates
      - ./static:/rss_reader/static
      - db:/db
    ports:
      - 8080:80
    environment:
      FLASK_ENV: development
      DEBUG: "true"
    command: >
      sh -c "uwsgi uwsgi.ini --py-autoreload 2"

  static:
    build:
      dockerfile_inline: |
        FROM node:20-bookworm

        USER node

        WORKDIR /home/node
        COPY static/package.json .
        RUN npm install --loglevel error
        ENV PATH=$PATH:/home/node/node_modules/.bin

        WORKDIR ./rss_reader
    volumes:
      - ./static:/home/node/rss_reader
    environment:
      SHELL: sh
    command: >
      sh -c "npm run build && npm run watch"

volumes:
  db:
