version: "3"
services:
  tests:
    build:
      context: .
      dockerfile: ./docker/tests.Dockerfile
    volumes:
      - ./app:/rss_reader
      - ./tests:/tests
    environment:
      SHELL: "sh"
      FLASK_ENV: "testing"
      SQLALCHEMY_DATABASE_URI: "sqlite:////:memory:"
    command: >
      sh -c "python -m pytest -v --color=yes /tests"
