version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./rss_reader:/rss_reader/
    ports:
      - 5000:5000
    environment:
      FLASK_APP: "."
      FLASK_ENV: "development"
      SECRET_KEY: "insecure"
      DATABASE_URI: "sqlite:////rss_reader/rss_reader.db"
  static:
    build:
      context: .
      dockerfile: ./docker/static/Dockerfile
    volumes:
      - ./rss_reader/static/src:/rss_reader/src
      - ./rss_reader/static/dist:/rss_reader/dist
    environment:
      SHELL: sh
    command: >
      sh -c "npm run build && npm run watch"
