version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    volumes:
      - ./app:/rss_reader/app
      - ./templates:/rss_reader/templates
      - ./static:/rss_reader/static
    ports:
      - 5000:5000
    env_file:
      - .env_default
      - .env
  static:
    build:
      context: .
      dockerfile: ./docker/static.Dockerfile
    volumes:
      - ./static/less:/rss_reader/less
      - ./static/ts:/rss_reader/ts
      - ./static/app.min.css:/rss_reader/app.min.css
      - ./static/app.min.js:/rss_reader/app.min.js
    environment:
      SHELL: sh
    command: >
      sh -c "npm run build && npm run watch"
