version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/rss-reader/
    expose:
      - 5000

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    environment:
      - NODE_ENV=development
      - SHELL=ash
    volumes:
        - ./frontend/src:/rss-reader/src
        - ./frontend/public:/rss-reader/public
    ports:
      - 8080:8080
    command: >
      ash -c "npm run build && npm run watch"
