version: "3"
services:
  rss_reader:
    build:
      context: .
      dockerfile: ./docker/rss_reader.Dockerfile
    volumes:
      - ./rss_reader:/rss_reader/
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: development
  static_dev:
    build:
      context: .
      dockerfile: ./docker/static_dev.Dockerfile
    volumes:
      - ./rss_reader/static/src:/rss_reader/src
      - ./rss_reader/static/dist:/rss_reader/dist
    environment:
      SHELL: sh
    command: >
      sh -c "npm run build && npm run watch"
