version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./rss_reader:/rss_reader/
    ports:
      - 5000:5000
    environment:
      FLASK_APP: .
      FLASK_ENV: development
      DATABASE_URI: sqlite:////tmp/rss_reader.db
    command: >
      sh -c "flask run --host=0.0.0.0"

  static_files:
    build:
      context: .
      dockerfile: Dockerfile.static_files
    volumes:
      - ./rss_reader/static/src:/rss_reader/src
      - ./rss_reader/static/public:/rss_reader/public
    environment:
      SHELL: sh
    depends_on:
      - app
    command: >
      sh -c "npm run build && npm run watch"
