version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/rss-reader/
    expose:
      - 5000

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    environment:
      - NODE_ENV=development
      - SHELL=bash
    volumes:
        - ./frontend/src:/rss-reader/src
    ports:
      - 8080:8080
