version: "3"
services:
  tests:
    build:
      context: .
      dockerfile: ./docker/tests/Dockerfile
    volumes:
      - ./rss_reader:/rss_reader
      - ./tests:/tests
    ports:
      - 5000:5000
    environment:
      FLASK_APP: "."
      SECRET_KEY: "insecure"
      DATABASE_URI: "sqlite:///:memory:"
