version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./rss_reader:/rss_reader/
    ports:
      - 5000:5000
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      DATABASE_URI: ${DATABASE_URI}
    command: >
      sh -c "flask run --host=${HOST}"

  static_builder:
    build:
      context: .
      dockerfile: ./docker/static_builder/Dockerfile
    volumes:
      - ./rss_reader/static/src:/rss_reader/src
      - ./rss_reader/static/dist:/rss_reader/dist
    environment:
      SHELL: sh
    depends_on:
      - app
    command: >
      sh -c "npm run build && npm run watch"
