version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./rss_reader:/rss_reader/
    ports:
      - 5000:5000
    env_file:
      - .env-dist
      - .env
    command: >
      sh -c "flask run --host=${HOST}"

  static_builder:
    build:
      context: .
      dockerfile: ./docker/static_builder/Dockerfile
    volumes:
      - ./rss_reader/static/src:/rss_reader/src
      - ./rss_reader/static/dist:/rss_reader/dist
    environment:
      SHELL: sh
    command: >
      sh -c "npm run build && npm run watch"
