version: "3"
services:
  tests:
    build:
      context: .
      dockerfile: ./docker/tests.Dockerfile
    volumes:
      - ./app:/app
      - ./tests:/tests
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: testing
      SQLALCHEMY_DATABASE_URI: "sqlite:////:memory:"

