version: "3"
services:
  tests:
    build:
      context: .
      dockerfile: ./docker/tests.Dockerfile
    volumes:
      - ./rss_reader:/rss_reader
      - ./tests:/tests
    environment:
      FLASK_ENV: testing
      DATABASE_URI: "sqlite:////:memory:"
