version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/tests/Dockerfile
    volumes:
      - ./rss_reader:/rss_reader
      - ./tests:/tests
    environment:
      TESTING: "True"
      DEBUG: "True"
      DATABASE_URI: "sqlite:///:memory:"
