version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    volumes:
      - ./app:/app/
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: development
  static_dev:
    build:
      context: .
      dockerfile: ./docker/static_dev.Dockerfile
    volumes:
      - ./app/static/src:/app/src
      - ./app/static/dist:/app/dist
    environment:
      SHELL: sh
    command: >
      sh -c "npm run build && npm run watch"
